variables:
  TASK: 'Task title'
  REPO: 'Repository with command to be run'
  RUN_CMD: 'Command in repository to be run'
  FILES: 'Files urls to be tested'
  DOCKER_IMAGE: 'Docker image to run tests in it'
  TIMEOUT: 'Timeout of running worker'
  OUTPUT_FILE: 'Run output'
  COURSE_ID: 'Course id'
  ISSUE_ID: 'Issue id'
  SSH_KEY_ID: 'SSH key id'

run:
  image: $DOCKER_IMAGE
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - cd easyci2/gitlabci
    - ./run_worker.sh "$TASK" "$REPO" "$RUN_CMD" "$FILES" "$TIMEOUT" "$OUTPUT_FILE" "$COURSE_ID" "$ISSUE_ID" "$SSH_KEY_ID"
  artifacts:
    paths:
      - easyci2/gitlabci/$OUTPUT_FILE
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'

